import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import ThemeProvider from "@/context/Theme";
import Navbar from "@/components/navbar/navbar";

const inter = localFont({
  src: "./fonts/inter.ttf",
  variable: "--font-inter",
  weight: "400 500 600 700 800 900",
});

const spaceGrotesk = localFont({
  src: "./fonts/grotesk.ttf",
  variable: "--font-space-grotesk",
  weight: "400 500 600 700",
});
export const metadata: Metadata = {
  title: "Devflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}>
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
